"""initial migration

Revision ID: 075de1f5c47a
Revises: 
Create Date: 2019-07-17 19:30:40.580656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075de1f5c47a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('latest_count', sa.Integer(), nullable=True),
    sa.Column('when_registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_latest_count'), 'site', ['latest_count'], unique=False)
    op.create_index(op.f('ix_site_name'), 'site', ['name'], unique=True)
    op.create_index(op.f('ix_site_when_registered'), 'site', ['when_registered'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forename', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('auth_level', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth_level'), 'user', ['auth_level'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_forename'), 'user', ['forename'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('last_call', sa.DateTime(), nullable=True),
    sa.Column('when_registered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_last_call'), 'camera', ['last_call'], unique=False)
    op.create_index(op.f('ix_camera_when_registered'), 'camera', ['when_registered'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=280), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_record_time'), 'record', ['record_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_record_time'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_camera_when_registered'), table_name='camera')
    op.drop_index(op.f('ix_camera_last_call'), table_name='camera')
    op.drop_table('camera')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_forename'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_auth_level'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_site_when_registered'), table_name='site')
    op.drop_index(op.f('ix_site_name'), table_name='site')
    op.drop_index(op.f('ix_site_latest_count'), table_name='site')
    op.drop_table('site')
    # ### end Alembic commands ###
