"""add site image location

Revision ID: 30f675d5401b
Revises: 075de1f5c47a
Create Date: 2019-07-19 20:45:02.652730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f675d5401b'
down_revision = '075de1f5c47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('image', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_site_image'), 'site', ['image'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_image'), table_name='site')
    op.drop_column('site', 'image')
    # ### end Alembic commands ###
